print("Intro to online selling here!")
print("First question...Which selling platform is the simplest to list?")
print("A: Ebay or B: Poshmark")
myAnswer = input()
print("Hmm... Interesting answer.")
print("Next question...Why do people sell online?")
print("A:Closet clearout B: Extra money C: Both")
input()
print("Oh! I like that answer!")
print("How will selling online now help you in the future?")
input()
print("In your experience, which is more fun to list and why?: Clothes or trinket")
input()
print("Thanks for taking this rockin' quiz, your future in retail awaits")
