print("Hello and welcome to the first annual Sonic quiz! Today you will be tested on your knowledge of Sonic!")
print(" And i am your one and only host... Sonic!")
print("First question is... When did sonic come out?")
myAnswer = input()
print("Hm? Your answer is " + (myAnswer) + " you say?")
input()
print("Next question... How does Sonic achieve his ultimate form Chaos Sonic?")
myanswer = input()
print("So you think that the answer is that " + (myanswer) + "?")
input()
print(" Whatever you say pal! Next question...Does Rouge have a crush on shadow or knuckles?")
input()
print("Ok last question!...how did the SonicX series end?")
input()
print("Now go to the real life Ayo and tell him that I said to check your answers")
